---
site_name: JGALabs
site_url: https://jakob1379.github.io
theme:
  # logo: assets/logo.png
  # favicon: images/favicon.png
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky  # always visible tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer
extra_css: [stylesheets/extra.css]
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jakob1379
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jakobaaes/
      name: LinkedIn
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/jakob1379/
      name: PyPi
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
plugins: [social, search, blog]
copyright: Copyright &copy; 2025 Jakob Stender Guldberg
markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
      # toc_depth: 3
