[dependency-groups]
dev = [
  "poethepoet>=0.36.0",
  "pre-commit>=4.2.0"
]

[project]
name = "jga-blog-page"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "mkdocs-material[imaging]>=9.6.16",
  "mkdocs>=1.6.1",
  "pymdown-extensions>=10.16.1",
  "rendercv[full]>=2.2"
]

[tool.poe.tasks]
# setup
_setup_pre-commit = "pre-commit install"
setup = {sequence = ["_setup_pre-commit"], help = "Setup dev environment"}
# update
_update_flake = "nix flake update"
_update_pre-commit = "pre-commit autoupdate -j0"
_update_python_packages = {shell = "uv sync --upgrade && uvx uv-bump"}
update = {sequence = ["_update_flake", "_update_pre-commit", "_update_python_packages"], help = "Update dependencies"}
# build
_build_mkdocs = 'mkdocs build'
_build_rendercv = {shell = 'rendercv render -o $(mktemp -d) --pdf-path site/assets/Jakob_Stender_Gulderg_CV.pdf ./cv/Jakob_Stender_Gulderg_CV.yml'}
build = {sequence = ["_build_mkdocs", "_build_rendercv"]}
# deploy
deploy = 'mkdocs gh-deploy'
