[project]
name = "jga-blog-page"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.6.16",
    "mkdocs>=1.6.1",
]

[dependency-groups]
dev = [
    "poethepoet>=0.36.0",
    "pre-commit>=4.2.0",
]
