---
name: mkdocs build and deploy
on:
  push:
    branches: [main]
permissions:
  contents: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Cache CV
        id: cache-cv
        uses: actions/cache@v4
        with:
          path: site/assets/Jakob_Stender_Guldberg_CV.pdf
          key: ${{ runner.os }}-cv-${{ hashFiles('cv/Jakob_Stender_Guldberg_CV.yml')
            }}
      - name: Render CV if not cached
        if: steps.cache-cv.outputs.cache-hit != 'true'
        run: nix develop -c -- uv run poe build
      - name: Build and Deploy Site
        run: nix develop -c -- uv run poe deploy
